title: 'Your awesome title'
author:
  name: 'GitHub User'
  email: 'mail@example.com'
description: 'Write an awesome description for your new site here.'

theme: 'ui-pages'

sass:
  style: compressed

plugins:
  - 'jekyll-github-metadata'
  - 'jekyll-seo-tag'
  - 'jekyll-sitemap'
  - 'jemoji'
